'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GlobaleLokalisierung
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EichsoftwareClient.GlobaleLokalisierung", GetType(GlobaleLokalisierung).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Synced successfully.
        '''</summary>
        Friend Shared ReadOnly Property Aktualisierung_Erfolgreich() As String
            Get
                Return ResourceManager.GetString("Aktualisierung_Erfolgreich", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Added or changed weighing instruments.
        '''</summary>
        Friend Shared ReadOnly Property Aktualisierung_NeuAWG() As String
            Get
                Return ResourceManager.GetString("Aktualisierung_NeuAWG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Aktualisierung_NeuEichung() As String
            Get
                Return ResourceManager.GetString("Aktualisierung_NeuEichung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Added or changed Load Cells.
        '''</summary>
        Friend Shared ReadOnly Property Aktualisierung_NeuWZ() As String
            Get
                Return ResourceManager.GetString("Aktualisierung_NeuWZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WI.
        '''</summary>
        Friend Shared ReadOnly Property AuswerteGeraet() As String
            Get
                Return ResourceManager.GetString("AuswerteGeraet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global Status.
        '''</summary>
        Friend Shared ReadOnly Property Bearbeitungsstatus() As String
            Get
                Return ResourceManager.GetString("Bearbeitungsstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please restart the application to complete the registration.
        '''</summary>
        Friend Shared ReadOnly Property BitteNeuStarten() As String
            Get
                Return ResourceManager.GetString("BitteNeuStarten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Eichfehlergrenzen werden nicht eingehalten. Der Vorgang kann nicht weitergeführt werden. (EN).
        '''</summary>
        Friend Shared ReadOnly Property EichfehlergrenzenNichtEingehalten() As String
            Get
                Return ResourceManager.GetString("EichfehlergrenzenNichtEingehalten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brückenabmessung Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Eichprotokoll_Dimension() As String
            Get
                Return ResourceManager.GetString("Eichprotokoll_Dimension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property EichprotokollZuruecksenden() As String
            Get
                Return ResourceManager.GetString("EichprotokollZuruecksenden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter &quot;1&quot;.
        '''</summary>
        Friend Shared ReadOnly Property EinsEintragen() As String
            Get
                Return ResourceManager.GetString("EinsEintragen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serial Number.
        '''</summary>
        Friend Shared ReadOnly Property Fabriknummer() As String
            Get
                Return ResourceManager.GetString("Fabriknummer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property Fehler() As String
            Get
                Return ResourceManager.GetString("Fehler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Der Vorgang kann nicht bearbeitet werden. Er ist schon als fehlerhaft markiert und wird bearbeitet.
        '''</summary>
        Friend Shared ReadOnly Property Fehler_EichprotokollBereitsAbgelehnt() As String
            Get
                Return ResourceManager.GetString("Fehler_EichprotokollBereitsAbgelehnt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Der Vorgang kann nicht bearbeitet werden. Er ist schon als genehmigt markiert.
        '''</summary>
        Friend Shared ReadOnly Property Fehler_EichprotokollBereitsGenehmigt() As String
            Get
                Return ResourceManager.GetString("Fehler_EichprotokollBereitsGenehmigt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte geben Sie eine gültige Genauigkeitsklasse ein (I,II,III,IV).
        '''</summary>
        Friend Shared ReadOnly Property Fehler_GenaugigkeitsklasseUnguelitg() As String
            Get
                Return ResourceManager.GetString("Fehler_GenaugigkeitsklasseUnguelitg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Es konnte kein passender Konformitätsbewertungsprozess gefunden werden. Bitte wenden Sie sich an RHEWA.
        '''</summary>
        Friend Shared ReadOnly Property Fehler_KeinServerObjektEichung() As String
            Get
                Return ResourceManager.GetString("Fehler_KeinServerObjektEichung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while loading data.
        '''</summary>
        Friend Shared ReadOnly Property Fehler_Laden() As String
            Get
                Return ResourceManager.GetString("Fehler_Laden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Der Konformitätsbewertungsvorgang konnte nicht gespeichert werden. Bitte rufen sie die aktuellsten Informationen von RHEWA ab und versuchen es erneut..
        '''</summary>
        Friend Shared ReadOnly Property Fehler_SpeicherAnomalie() As String
            Get
                Return ResourceManager.GetString("Fehler_SpeicherAnomalie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falls auch das nicht hilft, kontrollieren Sie den &quot;&quot;deaktiviert&quot;&quot; Status der Auswertegeräte und Wägezellen im Admin Client..
        '''</summary>
        Friend Shared ReadOnly Property Fehler_SpeicherAnomalieRhewaZusatztext() As String
            Get
                Return ResourceManager.GetString("Fehler_SpeicherAnomalieRhewaZusatztext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while saving data.
        '''</summary>
        Friend Shared ReadOnly Property Fehler_Speichern() As String
            Get
                Return ResourceManager.GetString("Fehler_Speichern", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid license. Please contact RHEWA.
        '''</summary>
        Friend Shared ReadOnly Property Fehler_UngueltigeLizenz() As String
            Get
                Return ResourceManager.GetString("Fehler_UngueltigeLizenz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Question.
        '''</summary>
        Friend Shared ReadOnly Property Frage() As String
            Get
                Return ResourceManager.GetString("Frage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Möchten Sie den gewählten Konformitätsbewertungsprozess wirklich ablehnen? Der Eichbevollmächtigte kriegt diesen dann zur erneuten Bearbeitung zugesandt.
        '''</summary>
        Friend Shared ReadOnly Property Frage_Ablehnen() As String
            Get
                Return ResourceManager.GetString("Frage_Ablehnen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Möchten Sie das korrigierte Messprotokoll wirklich an den Eichbevollmächtigten zurücksenden? Der Status wird dabei auf fehlerhaft gesetzt..
        '''</summary>
        Friend Shared ReadOnly Property Frage_EichprotokollZuruecksenden() As String
            Get
                Return ResourceManager.GetString("Frage_EichprotokollZuruecksenden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Möchten Sie den gewählten Konformitätsbewertungsprozess wirklich genehmigen? Er gilt dann als abgeschlossen und kann nicht mehr bearbeitet werden.
        '''</summary>
        Friend Shared ReadOnly Property Frage_Genehmigen() As String
            Get
                Return ResourceManager.GetString("Frage_Genehmigen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Möchten Sie den gewählten Konformitätsbewertungsprozess kopieren um ihn als Vorlage zu verwenden?.
        '''</summary>
        Friend Shared ReadOnly Property Frage_Kopieren() As String
            Get
                Return ResourceManager.GetString("Frage_Kopieren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Auswahlliste() As String
            Get
                Return ResourceManager.GetString("Hilfe_Auswahlliste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This inspection applies to the in-process control of all weighing instruments that are assembled or modified by
        ''' RHEWA personnel or on our behalf by authorised representatives integrated in the RHEWA QM system.
        '''
        ''' The responsible or authorised employee shall check the criteria listed below in full.
        '''
        ''' A part is non-conforming if a characteristic is out of specification.
        ''' If the number of non-conforming parts equals 0, the weighing instruments are released for verification.
        ''' If the number of non-conform [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Beschaffenheitspruefung() As String
            Get
                Return ResourceManager.GetString("Hilfe_Beschaffenheitspruefung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe Eichprotokoll_Stammdaten EN.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_EichprotokollStammdaten() As String
            Get
                Return ResourceManager.GetString("Hilfe_EichprotokollStammdaten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_Eichprotokollverfahrensauswahl EN.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Eichprotokollverfahrensauswahl() As String
            Get
                Return ResourceManager.GetString("Hilfe_Eichprotokollverfahrensauswahl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Data into Excel and Word Templates.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Exports() As String
            Get
                Return ResourceManager.GetString("Hilfe_Exports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe Hauptmenü EN.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Hauptmenue() As String
            Get
                Return ResourceManager.GetString("Hilfe_Hauptmenue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cable connection (4- or 6-wire) between
        ''' load cell junction box and indicator
        '''
        ''' The original 4-wire load cell cable have to be kept in any case,
        '''
        ''' The connection of original 4-wire load cell cables just beside the indicator is also allowed in any case.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGAnschlussart() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGAnschlussart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fraction of the maximum permissible error of the weighing instrument used for the indicator
        ''' according to R76 No 3.5.4
        ''' standard pind = 0,5 ; allowable 0,3 &gt; pind &gt; 0,8.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGBruchteilEichfehlergrenze() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGBruchteilEichfehlergrenze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to upper limit of the impedance
        ''' for the load cell(s) to be supplied
        ''' (limitted by sensitivity against EMC)
        ''' Indicator 83N ges.5000 Ohm
        ''' Indicator 83+ ges.5000 Ohm
        ''' Indicator 83Z ges.5000 Ohm
        ''' Indicator 84 ges.5000 Ohm
        ''' Indicator 82a ges.3300 Ohm
        ''' Indicator 82b,c,e ges.5250 Ohm.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGGrenzwerteLastwiderstandMax() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGGrenzwerteLastwiderstandMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to lower limit of the impedance of the load cell(s) to be supplied
        ''' the load cells are connected in parallel
        ''' (limitted by power supply fittted by the indicator)
        '''
        ''' Indicator 83 N ges. 87 Ohm
        ''' Indicator 83 plus ges. 87 Ohm
        ''' Indicator 83 Z ges. 35 Ohm
        ''' Indicator 84 ges. 44 Ohm
        ''' Indicator 82a ges. 50 Ohm
        ''' Indicator 82b,c,e ges. 40 Ohm.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGGrenzwerteLastwiderstandMin() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGGrenzwerteLastwiderstandMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximal allowed ratio of cable length per wire cross section
        '''
        ''' Indicator 83 N 116 m/mm²
        ''' Indicator 83 plus 116 m/mm²
        ''' Indicator 83Z 440 m/mm²
        ''' Indicator 84 110 m/mm²
        ''' Indicator 82a 750 m/mm²
        ''' Indicator 82b,c,e 54,2 m/mm²
        '''
        ''' see comment to cross section of wire A.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGKabellaenge() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGKabellaenge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;p&gt;Accuracy class:&lt;br /&gt;The accuracy classes of NAWI, Ind and LCs are compatible, if they follow table below:&lt;/p&gt;&lt;p&gt;&lt;strong&gt; NAWI I II III IIII&lt;br /&gt; Ind I I*), II II*), III III, IIII&lt;br /&gt; LC A A*), B B*), C C, D&lt;/strong&gt;&lt;br /&gt; &lt;br /&gt; *) at sufficient temperature range and evaluation of stability against &lt;br /&gt; humidity and creep correspond to requirement in the lower &lt;br /&gt; (more accurate) class&lt;/p&gt;&lt;/html&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGKlasse() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGKlasse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to the indicator may need a minimum input voltage at all (bias),
        ''' if so the value is given in the indicator documentation;
        ''' this indicator is not able to measure changing polarity of voltage
        '''
        ''' If no Umin is required insert 0.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGMindesteingangsspannung() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGMindesteingangsspannung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The minimum value allowed for the signal voltage per verification scale interval is:
        '''
        ''' Indicator 83N 0,5üV/ e
        ''' Indicator 83+ 0,5 üV/ e
        ''' Indicator 83Z 0,6 üV/ e
        ''' Indicator 84 0,7 üV/ e
        ''' Indicator 82a 0,5 üV/ e
        ''' Indicator 82b,c,e 0,3 üV/ e.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGMindestmesssignal() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGMindestmesssignal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excitation power supply for the load cell(s)
        '''
        ''' Indicator 83N 8V
        ''' Indicator 83+ 8V
        ''' Indicator 84 8V
        ''' Indicator 83Z 12V
        ''' Indicator 82a,b,c,e 5V
        '''
        ''' Note:
        ''' Insert total voltage, wrong + 5 V
        '''                                    correct 10 V
        '''
        ''' Further see comment for cross section A.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGSpeisespannung() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGSpeisespannung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to maximal number of verification scale intervals for the indicator:
        '''
        '''                           single -range/interval multi -range/interval
        ''' accuracy-
        ''' class III IV III IV
        ''' Gerät
        ''' 83+/83Z/84 10000 1000 3000 1000
        ''' 82a,b,c,e 10000 1000 6000 1000
        '''
        ''' maximum of 3 partial ranges
        '''
        ''' The maximal number n ind of verification scale intervals of the indicator must be equal or better than the number of verification scale intervals of the weighing instrument n = Max/e.
        ''' For multiple range and muti-interval wei [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGTeilungswerte() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGTeilungswerte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to limit of the temperature range
        ''' upper limit of the environment temperature
        ''' for the indicator.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGTemperaturbereichMax() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGTemperaturbereichMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to limit of the temperature range
        ''' lower limit of the environment temperature
        ''' for the indicator.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_AWGTemperaturbereichMin() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_AWGTemperaturbereichMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fraction of the maximum permissible error of the weighing instrument
        ''' applied for connecting elements pcon ,
        ''' For the fraction of all unknown mechanical and electrical connection elements between load receptor, load cell(s) a d indicator.
        '''
        '''  acceptable according to R76 No 3.4.5 pcon = 0,5.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_VerbindungselementeBruchteilEichfehlergrenze() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_VerbindungselementeBruchteilEichfehlergrenze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to maximum value of the additive tare device (if existing)
        '''
        ''' if no device of Additive Tare, fill out with 0.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageAdditiveTarahoechstlast() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageAdditiveTarahoechstlast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to number of load cells.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageAnzahlWaegezellen() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageAnzahlWaegezellen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;p&gt;factor NUD: (WI = weighing instrument, LC = load cell)&lt;/p&gt;&lt;p&gt;Factor for &lt;strong&gt;N&lt;/strong&gt;on &lt;strong&gt;U&lt;/strong&gt;niform &lt;strong&gt;D&lt;/strong&gt;istributed load caused by excentric loading,&lt;br /&gt;NUD shall prohibit that a load cell is applied with load outside of the garanteed measuring range.&lt;/p&gt;&lt;p&gt;According to WELMEC 2 (Issue 3) Nr. 3.1.6.6 followig values may be accepted for NUD:&lt;br /&gt;- WIs with lever work and with one LC, WIs with one single point LC and&lt;br /&gt; WIs with load receptors which allöw only min [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageEcklastzuschlag() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageEcklastzuschlag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum capacity of One range weighing instrument.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageEichwert() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageEichwert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to verification interval of the lower weighing range
        ''' of a multiple range or multi-interval weighing instrument.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageEichwert1() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageEichwert1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to verification interval of the 2nd weighing range of
        ''' multiple range or multi-interval weighing instrument
        ''' (e 1 = smallest weighing range).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageEichwert2() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageEichwert2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to verification interval of the upper weighing range of multi-interval weighing instrument
        ''' (e1 = smallest verification interval).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageEichwert3() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageEichwert3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;p&gt;Function for setting the indication to zero at&lt;br /&gt;the time the indicator is switched on.&lt;br /&gt;&lt;strong&gt;Standard setting Rhewa:&lt;br /&gt;15% upper limit for permissible initial zero setting&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;&lt;strong&gt; 3kg = 0,450kg&lt;br /&gt; 6kg = 0,900kg&lt;br /&gt; 15kg = 2,250kg&lt;br /&gt; 30kg = 4,5kg&lt;br /&gt; 60kg = 9,0kg&lt;br /&gt; 150kg = 22,5kg&lt;br /&gt; 300kg = 45kg&lt;br /&gt; 600kg = 90kg&lt;br /&gt; 1500kg = 225kg&lt;br /&gt; 3000kg = 450kg&lt;br /&gt; 6000kg = 900kg &lt;br /&gt;15000kg = 2250kg&lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;&lt;/html&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageEinschaltnullstellbereich() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageEinschaltnullstellbereich", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to verification interval of
        ''' One range weighing instrument.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageHoechstlast() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageHoechstlast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum capacity of the lower weighing range of multiple range or multi-interval weighing instrument.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageHoechstlast1() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageHoechstlast1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum capacity of the 2nd weighing range of
        ''' multipe range or multi-interval weighing instruments
        '''  (Max1 = lower weighing range).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageHoechstlast2() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageHoechstlast2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum capacity of the upper weighing range
        ''' of multiple range or multi-interval weighing instruments
        '''  (Max1 = lower weighing range).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageHoechstlast3() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageHoechstlast3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to length of cable
        ''' length of cable between indicator and load cell junction box
        ''' ( load cell cables themselves have to maintain original).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageKabellaenge() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageKabellaenge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cross section of wire
        ''' cross section of one wire from cable (4 or 6 wires)
        ''' between indicator and load cell junction box
        '''
        ''' Note
        ''' - By application of different cross sections in one cable use
        '''            for 4-wires the supply wires
        '''            for 6-wires the reference wires
        ''' - Using flash protection elements, the exitation voltage at the load cell
        '''            has to be checked when applying check on condition (8).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageKabelquerschnitt() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageKabelquerschnitt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;p&gt;Accuracy class:&lt;br /&gt;The accuracy classes of NAWI, Ind and LCs are compatible, if they follow table below:&lt;/p&gt;&lt;p&gt;&lt;strong&gt; NAWI I II III IIII&lt;br /&gt; Ind I I*), II II*), III III, IIII&lt;br /&gt; LC A A*), B B*), C C, D&lt;/strong&gt;&lt;br /&gt; &lt;br /&gt; *) at sufficient temperature range and evaluation of stability against &lt;br /&gt; humidity and creep corresponds to requirement in the lower &lt;br /&gt; (more accurate) class&lt;/p&gt;&lt;/html&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageKlasse() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageKlasse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to limit of the temperature range
        ''' upper limit of the environment temperature
        ''' for the whole weighing instrument.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageTemperaturbereichMAX() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageTemperaturbereichMAX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to limit of the temperature range
        ''' lower limit of the environment temperature
        ''' for the whole weighing instrument.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageTemperaturbereichMin() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageTemperaturbereichMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dead load:
        ''' weight of the load receptor and additionally mounted constructions on the load receptor.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageTotlast() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageTotlast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to reduction ratio R
        ''' The reduction ratio is given by a lever work system.
        '''
        ''' According to R76 No T.3.3
        ''' R = (Force onto the load cell)/(Gravitation force onto the load receptor)
        '''
        ''' Using lever works normally the number N of load cells is N = 1 and R &lt; 1
        ''' The value of R has to be given by the WI-manufacturer
        ''' Without lever system the reduction ratio R always will be R = 1
        '''
        ''' Format of Field: Number
        ''' Excample of wrong format 1:4, inputs with &quot;:&quot; will be treated as time
        '''                     correct form [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WaageUebersetzungsverhaeltnis() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WaageUebersetzungsverhaeltnis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fraction of the maximum permissible error of the weighing instrument
        ''' applied for the load cells
        ''' if not indicated in the test certificate , pLC = 0,7..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZBruchteilEichfehlergrenze() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZBruchteilEichfehlergrenze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;p&gt;Accuracy class:&lt;br /&gt;The accuracy classes of NAWI, Ind and LCs are compatible, if they follow table below:&lt;/p&gt;&lt;p&gt;&lt;strong&gt; NAWI I II III IIII&lt;br /&gt; Ind I I*), II II*), III III, IIII&lt;br /&gt; LC A A*), B B*), C C, D&lt;/strong&gt;&lt;br /&gt; &lt;br /&gt; *) at sufficient temperature range and evaluation of stability against &lt;br /&gt; humidity and creep correspond to requirement in the lower &lt;br /&gt; (more accurate) class&lt;/p&gt;&lt;/html&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZGenauigkeitsklasse() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZGenauigkeitsklasse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;maximum capacity of one load cell&lt;br /&gt;The maximum capacity of the load cell shall not be exeeded when applying Max on the weighing instrument.&lt;br /&gt; capacity &lt;br /&gt; &lt;strong&gt; Kg N lb&lt;/strong&gt;&lt;br /&gt; &lt;span style=&quot;color: #0080ff&quot;&gt; 20,4 200&lt;/span&gt;&lt;br /&gt; &lt;span style=&quot;color: #0080c0&quot;&gt; 51 500&lt;/span&gt; &lt;br /&gt;&lt;span style=&quot;color: #ff0000&quot;&gt; 91 200&lt;/span&gt;&lt;br /&gt; &lt;span style=&quot;color: #0080ff&quot;&gt; 102 1000 &lt;br /&gt; 204 2000 &lt;br /&gt;&lt;/span&gt;&lt;span style=&quot;color: #ff0000&quot;&gt; 227 500 &lt;br /&gt; 454 1000&lt;/span&gt; &lt;br /&gt; &lt;span style=&quot;color:  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZHoechstlast() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZHoechstlast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ratio of Emax / vmin of the load cell
        '''
        ''' If Y or vmin is not indicated (f.e. in the test certificate), nLC will be used instead of Y ..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZHoechstteilungsfaktor() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZHoechstteilungsfaktor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ratio of Emax / 2* DR of the load cell
        ''' Where DR or Z not known
        ''' (f.e. not indicated in the test certificate),
        ''' nLC will be used instead of Z..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZKriechteilungsfaktor() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZKriechteilungsfaktor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to maximal number of verification scale intervals of the load cell:
        ''' The max. number nLC of verification scale intervals of the load cell must be equal or better than the number of verification scale intervals of the weighing instrument n = Max/e.
        ''' For multiple range and muti-interval weighing instruments this must be met for every weighing range..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZMaxTeilungswerte() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZMaxTeilungswerte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minimum dead load of one load cell
        '''
        ''' the applied dead load on the load cell in the WI must be
        ''' bigger or equal to the minimum dead load of the load cell
        '''
        ''' when Emin = 0 insert 0.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZMindestvorlast() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZMindestvorlast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to smallest verification interval of one load cell
        ''' If Y or vmin is not indicated (f.e. in the test certificate), nLC will be used instead of Y ..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZMinTeilungswert() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZMinTeilungswert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minimum dead load return of the load cell:
        ''' Where DR or Z not known
        ''' (f.e. not indicated in the test certificate),
        ''' nLC will be used instead of Z..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZRueckkehrVorlastsignal() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZRueckkehrVorlastsignal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to limit of the temperature range
        ''' upper limit of the environment temperature
        ''' for the load cell.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZTemperaturbereichMAX() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZTemperaturbereichMAX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to limit of the temperature range
        ''' lower limit of the environment temperature
        ''' for the load cell.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZTemperaturbereichMIN() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZTemperaturbereichMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rated output of the load cell
        ''' when loading with maximum capacity (in mV/V).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZWaegezellenkennwert() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZWaegezellenkennwert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Input impedance of one load cell:
        '''
        ''' The WI may have N load cells.
        ''' The smallest ratio of RLC / N is limitted
        ''' by the power supply of the indicator.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Kompatiblitaetsnachweis_WZWiderstand() As String
            Get
                Return ResourceManager.GetString("Hilfe_Kompatiblitaetsnachweis_WZWiderstand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_KompatiblitaetsnachweisErgebnisHilfe() As String
            Get
                Return ResourceManager.GetString("Hilfe_KompatiblitaetsnachweisErgebnisHilfe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_KompatiblitaetsnachweisHilfe() As String
            Get
                Return ResourceManager.GetString("Hilfe_KompatiblitaetsnachweisHilfe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;p&gt;&lt;strong&gt;4.5.2 Accuracy&lt;/strong&gt;&lt;br /&gt;After zero setting the effect of zero deviation on the result of the weighing shall be not more than ± 0.25 e.&lt;/p&gt;&lt;p&gt;&lt;strong&gt;A.4.2.3 Accuracy of zero-setting (4.5.2)&lt;/strong&gt;&lt;br /&gt;The test may be combined with A.4.4.1.&lt;/p&gt;&lt;p&gt;&lt;strong&gt;A.4.2.3.1 Non-automatic and semi-automatic zero-setting&lt;/strong&gt;&lt;br /&gt;The accuracy of the zero-setting device is tested by first loading the instrument to an indication as close as possible to a changeover point, and then by initiati [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Nullstellung() As String
            Get
                Return ResourceManager.GetString("Hilfe_Nullstellung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PRuefungAnsprechvermoegen (EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungAnsprechvermoegen() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungAnsprechvermoegen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PrüfungAussermittigerBelastung(EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungAussermittigerBelastung() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungAussermittigerBelastung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PruefungDerRichtigkeitMitNormallast(EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungDerRichtigkeitMitNormallast() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungDerRichtigkeitMitNormallast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PruefungDerWiederholbarkeit.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungDerWiederholbarkeit() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungDerWiederholbarkeit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PRuefungEichtechnischeSicherung (EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungEichtechnischeSicherung() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungEichtechnischeSicherung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qualification for axle load weighing.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungEignungAchslastwaegungen() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungEignungAchslastwaegungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PRuefungFallbeschleunigung (EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungFallbeschleunigung() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungFallbeschleunigung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PruefungRollendeLasten (EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungRollendeLasten() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungRollendeLasten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PruefungStabilitaet (EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungStabilitaet() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungStabilitaet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PruefungStaffelverfahren (EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungStaffelverfahren() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungStaffelverfahren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ablesen und eintragen des Anzeigewertes nach Abnahme der aufgebrachten Normallast..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungStaffelverfahrenErsatzlastErsatzlast2() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungStaffelverfahrenErsatzlastErsatzlast2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ablesen und eintragen des Anzeigewertes der mit entsprechender Ersatzlast und deraufgebrachten Normallast nachgebildet wurde..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungStaffelverfahrenErsatzlastErsatzPlusNormallast() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungStaffelverfahrenErsatzlastErsatzPlusNormallast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ablesen und eintragen des Anzeigewertes der mit entsprechender Ersatzlast nachgebildet wurde. Abweichungen von maximal ±10e möglich.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungStaffelverfahrenErsatzlastIst() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungStaffelverfahrenErsatzlastIst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eintragung der zur Verfügung stehenden vollen Normallast oder des Betrages der benötigt wird um die Höchstlast der Waage zu erreichen..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungStaffelverfahrenErsatzlastNormallast() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungStaffelverfahrenErsatzlastNormallast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eintragung des Wertes der mit einer Ersatzlast nachgebildet werden soll..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungStaffelverfahrenErsatzlastSoll() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungStaffelverfahrenErsatzlastSoll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ablesen und eintragen des Anzeigewertes der aufgebrachten Normallast..
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungStaffelverfahrenNormallast() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungStaffelverfahrenNormallast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to by lever works testing the tare function in accordance to EN 45501 Nr. 3.5.3.3 - 3.5.3.4, A 4.6.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungTaraEinrichtung() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungTaraEinrichtung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hilfe_PruefungUeberlastAnzeige (EN).
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungUeberlastAnzeige() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungUeberlastAnzeige", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Determine the allowed number of substitutions according to EN 45501 3.7.3.
        '''
        ''' If the repeatability error is not greater than 0.2 e, this portion may be reduced to 1/5 Max.
        ''' If the repeatability error is not greater than 0.35 e, the portion of standard weights may
        ''' be reduced to 1/3 Max.
        ''' If the repeatability error is greater than 0.35 e, the portion of standard weights must 50%.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_PruefungWiederholbarkeitStaffelverfahren() As String
            Get
                Return ResourceManager.GetString("Hilfe_PruefungWiederholbarkeitStaffelverfahren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Stammdaten() As String
            Get
                Return ResourceManager.GetString("Hilfe_Stammdaten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create a new Load Cell.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_StammdatenNeueWZ() As String
            Get
                Return ResourceManager.GetString("Hilfe_StammdatenNeueWZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send Data to RHEWA.
        '''</summary>
        Friend Shared ReadOnly Property Hilfe_Versenden() As String
            Get
                Return ResourceManager.GetString("Hilfe_Versenden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot establish connection to RHEWA Server. Make sure you are connected to the internet and try again..
        '''</summary>
        Friend Shared ReadOnly Property KeineVerbindung() As String
            Get
                Return ResourceManager.GetString("KeineVerbindung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch Kompatilbität.
        '''</summary>
        Friend Shared ReadOnly Property KompatiblitätNichtGeleistet() As String
            Get
                Return ResourceManager.GetString("KompatiblitätNichtGeleistet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please fill in all required fields.
        '''</summary>
        Friend Shared ReadOnly Property PflichtfelderAusfuellen() As String
            Get
                Return ResourceManager.GetString("PflichtfelderAusfuellen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quality inspection.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_Beschaffenheitspruefung() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_Beschaffenheitspruefung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_EichprotokollStammdaten() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_EichprotokollStammdaten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verification type.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_Eichprotokollverfahrensauswahl() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_Eichprotokollverfahrensauswahl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Data.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_Exports() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_Exports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_Hauptmenue() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_Hauptmenue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_Kompatiblitaetsnachweis() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_Kompatiblitaetsnachweis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_KompatiblitaetsnachweisErgebnis() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_KompatiblitaetsnachweisErgebnis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungAnsprechvermoegen (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungAnsprechvermoegen() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungAnsprechvermoegen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prüfung der Richtigkeit mit Normallast(EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungDerRichtigkeitMitNormallast() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungDerRichtigkeitMitNormallast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungDerWiederholbarkeit.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungDerWiederholbarkeit() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungDerWiederholbarkeit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungEichtechnischeSicherung (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungEichtechnischeSicherung() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungEichtechnischeSicherung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qualification for axle load weighing.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungEignungAchslastwaegungen() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungEignungAchslastwaegungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungFallbeschleunigung (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungFallbeschleunigung() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungFallbeschleunigung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Messtechnische Prüfung (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungNullstellungundAussermittigeBelastung() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungNullstellungundAussermittigeBelastung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungRollendelasten (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungRollendelasten() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungRollendelasten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungStabilitaet (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungStabilitaet() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungStabilitaet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungStaffelverfahren (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungStaffelverfahren() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungStaffelverfahren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungTaraEinrichtung (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungTaraEinrichtung() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungTaraEinrichtung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ueberschrift_PruefungUeberlastAnzeige (EN).
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_PruefungUeberlastAnzeige() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_PruefungUeberlastAnzeige", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_Stammdaten() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_Stammdaten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send Data to RHEWA.
        '''</summary>
        Friend Shared ReadOnly Property Ueberschrift_Versenden() As String
            Get
                Return ResourceManager.GetString("Ueberschrift_Versenden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Waagenart() As String
            Get
                Return ResourceManager.GetString("Waagenart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Englisch.
        '''</summary>
        Friend Shared ReadOnly Property Waagentyp() As String
            Get
                Return ResourceManager.GetString("Waagentyp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Cell.
        '''</summary>
        Friend Shared ReadOnly Property Waegezelle() As String
            Get
                Return ResourceManager.GetString("Waegezelle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choosing &apos;Yes&apos; will delete remaining unsent assessments. Are you sure you want to resync your data, while loosing unsent assesments?.
        '''</summary>
        Friend Shared ReadOnly Property Warnung_EichungenWerdenGeloescht() As String
            Get
                Return ResourceManager.GetString("Warnung_EichungenWerdenGeloescht", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
