'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mogelstatistik
    Public Property ID As Integer
    Public Property FK_Eichprozess As Nullable(Of Integer)
    Public Property FK_Auswertegeraet As String
    Public Property FK_Waegezelle As String
    Public Property Kompatiblitaet_Waage_FabrikNummer As String
    Public Property Kompatiblitaet_Waage_Bauartzulassung As String
    Public Property Kompatiblitaet_Waage_Revisionsnummer As String
    Public Property Kompatiblitaet_Waage_Zulassungsinhaber As String
    Public Property Kompatiblitaet_Waage_Genauigkeitsklasse As String
    Public Property Kompatiblitaet_Waage_AdditiveTarahoechstlast As String
    Public Property Kompatiblitaet_Waage_GrenzenTemperaturbereichMIN As String
    Public Property Kompatiblitaet_Waage_GrenzenTemperaturbereichMAX As String
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertMax_Bereich1 As String
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertE_Bereich1 As String
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertMax_Bereich2 As String
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertE_Bereich2 As String
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertMax_Bereich3 As String
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertE_Bereich3 As String
    Public Property Kompatiblitaet_Waage_Uebersetzungsverhaeltnis As String
    Public Property Kompatiblitaet_Waage_AnzahlWaegezellen As String
    Public Property Kompatiblitaet_Waage_Einschaltnullstellbereich As String
    Public Property Kompatiblitaet_Waage_Ecklastzuschlag As String
    Public Property Kompatiblitaet_Waage_Totlast As String
    Public Property Kompatiblitaet_Waage_Kabellaenge As String
    Public Property Kompatiblitaet_Waage_Kabelquerschnitt As String
    Public Property Kompatiblitaet_AnschriftWaagenbaufirma As String
    Public Property Kompatiblitaet_Verbindungselemente_BruchteilEichfehlergrenze As String
    Public Property Kompatiblitaet_AWG_Anschlussart As String
    Public Property Kompatiblitaet_WZ_Hoechstlast As String

    Public Overridable Property Eichprozess As Eichprozess
    Public Overridable Property Lookup_Auswertegeraet As Lookup_Auswertegeraet
    Public Overridable Property Lookup_Waegezelle As Lookup_Waegezelle

End Class
