'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerEichmarkenverwaltung
    Public Property ID As Integer
    Public Property FK_SuperofficeBenutzer As String
    Public Property BenannteStelleAnzahl As Nullable(Of Integer)
    Public Property Eichsiegel13x13Anzahl As Nullable(Of Integer)
    Public Property EichsiegelRundAnzahl As Nullable(Of Integer)
    Public Property HinweismarkeGelochtAnzahl As Nullable(Of Integer)
    Public Property GruenesMAnzahl As Nullable(Of Integer)
    Public Property CEAnzahl As Nullable(Of Integer)
    Public Property BenannteStelleAnzahlMeldestand As Nullable(Of Integer)
    Public Property Eichsiegel13x13AnzahlMeldestand As Nullable(Of Integer)
    Public Property EichsiegelRundAnzahlMeldestand As Nullable(Of Integer)
    Public Property HinweismarkeGelochtAnzahlMeldestand As Nullable(Of Integer)
    Public Property GruenesMAnzahlMeldestand As Nullable(Of Integer)
    Public Property CEAnzahlMeldestand As Nullable(Of Integer)
    Public Property zerstoerteMarke0103 As Nullable(Of Integer)
    Public Property FehlmengeSicherungsmarkeklein As Nullable(Of Integer)
    Public Property FehlmengeSicherungsmarkegross As Nullable(Of Integer)
    Public Property FehlmengeHinweismarken As Nullable(Of Integer)

End Class
