'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Benutzer
    Public Property ID As string
    Public Property Vorname As string
    Public Property Nachname As string
    Public Property Telefon As string
    Public Property HEKennung As string
    Public Property Firma_FK As string

    Public Overridable Property Firmen As Firmen
    Public Overridable Property ServerLizensierung As ICollection(Of ServerLizensierung) = New HashSet(Of ServerLizensierung)

End Class
