'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class HerstellerersteichungEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=HerstellerersteichungEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Benutzer() As DbSet(Of Benutzer)
    Public Overridable Property Firmen() As DbSet(Of Firmen)
    Public Overridable Property ServerAblageEichprozesse() As DbSet(Of ServerAblageEichprozesse)
    Public Overridable Property ServerEichmarkenverwaltung() As DbSet(Of ServerEichmarkenverwaltung)
    Public Overridable Property ServerEichprotokoll() As DbSet(Of ServerEichprotokoll)
    Public Overridable Property ServerEichprozess() As DbSet(Of ServerEichprozess)
    Public Overridable Property ServerFirmenZusatzdaten() As DbSet(Of ServerFirmenZusatzdaten)
    Public Overridable Property ServerKompatiblitaetsnachweis() As DbSet(Of ServerKompatiblitaetsnachweis)
    Public Overridable Property ServerKonfiguration() As DbSet(Of ServerKonfiguration)
    Public Overridable Property ServerLizensierung() As DbSet(Of ServerLizensierung)
    Public Overridable Property ServerLookup_Auswertegeraet() As DbSet(Of ServerLookup_Auswertegeraet)
    Public Overridable Property ServerLookup_Bearbeitungsstatus() As DbSet(Of ServerLookup_Bearbeitungsstatus)
    Public Overridable Property ServerLookup_Konformitaetsbewertungsverfahren() As DbSet(Of ServerLookup_Konformitaetsbewertungsverfahren)
    Public Overridable Property ServerLookup_Vorgangsstatus() As DbSet(Of ServerLookup_Vorgangsstatus)
    Public Overridable Property ServerLookup_Waagenart() As DbSet(Of ServerLookup_Waagenart)
    Public Overridable Property ServerLookup_Waagentyp() As DbSet(Of ServerLookup_Waagentyp)
    Public Overridable Property ServerLookup_Waegezelle() As DbSet(Of ServerLookup_Waegezelle)
    Public Overridable Property ServerLookupVertragspartnerFirma() As DbSet(Of ServerLookupVertragspartnerFirma)
    Public Overridable Property ServerMogelstatistik() As DbSet(Of ServerMogelstatistik)
    Public Overridable Property ServerPruefungAnsprechvermoegen() As DbSet(Of ServerPruefungAnsprechvermoegen)
    Public Overridable Property ServerPruefungAussermittigeBelastung() As DbSet(Of ServerPruefungAussermittigeBelastung)
    Public Overridable Property ServerPruefungLinearitaetFallend() As DbSet(Of ServerPruefungLinearitaetFallend)
    Public Overridable Property ServerPruefungLinearitaetSteigend() As DbSet(Of ServerPruefungLinearitaetSteigend)
    Public Overridable Property ServerPruefungRollendeLasten() As DbSet(Of ServerPruefungRollendeLasten)
    Public Overridable Property ServerPruefungStabilitaetGleichgewichtslage() As DbSet(Of ServerPruefungStabilitaetGleichgewichtslage)
    Public Overridable Property ServerPruefungStaffelverfahrenErsatzlast() As DbSet(Of ServerPruefungStaffelverfahrenErsatzlast)
    Public Overridable Property ServerPruefungStaffelverfahrenNormallast() As DbSet(Of ServerPruefungStaffelverfahrenNormallast)
    Public Overridable Property ServerPruefungWiederholbarkeit() As DbSet(Of ServerPruefungWiederholbarkeit)
    Public Overridable Property ServerVerbindungsprotokoll() As DbSet(Of ServerVerbindungsprotokoll)
    Public Overridable Property ServerVerbindungsprotokollArchiv() As DbSet(Of ServerVerbindungsprotokollArchiv)
    Public Overridable Property StatusPrüfscheinnummer() As DbSet(Of StatusPrüfscheinnummer)

End Class
