'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Firmen
    Public Property ID As string
    Public Property KundenNr As string
    Public Property Name As string
    Public Property Strasse As string
    Public Property PLZ As string
    Public Property Telefon As string
    Public Property Ort As string
    Public Property Land As string

    Public Overridable Property ServerFirmenZusatzdaten As ICollection(Of ServerFirmenZusatzdaten) = New HashSet(Of ServerFirmenZusatzdaten)
    Public Overridable Property Benutzer As ICollection(Of Benutzer) = New HashSet(Of Benutzer)

End Class
