'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerAblageEichprozesse
    Public Property id As Integer
    Public Property Lizenz As String
    Public Property HEKennung As String
    Public Property Vorgangsnummer As String
    Public Property JSON As String

End Class
