'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerLookup_Auswertegeraet
    Public Property ID As string
    Public Property Typ As string
    Public Property Hersteller As string
    Public Property Pruefbericht As string
    Public Property Bauartzulassung As string
    Public Property Genauigkeitsklasse As string
    Public Property MAXAnzahlTeilungswerteEinbereichswaage As string
    Public Property MAXAnzahlTeilungswerteMehrbereichswaage As string
    Public Property Speisespannung As string
    Public Property Mindesteingangsspannung As string
    Public Property Mindestmesssignal As string
    Public Property GrenzwertLastwiderstandMIN As string
    Public Property GrenzwertLastwiderstandMAX As string
    Public Property GrenzwertTemperaturbereichMIN As string
    Public Property GrenzwertTemperaturbereichMAX As string
    Public Property BruchteilEichfehlergrenze As string
    Public Property KabellaengeQuerschnitt As string
    Public Property ErstellDatum As Nullable(Of Date)
    Public Property Deaktiviert As Boolean
    Public Property TaraeinrichtungTaraeingabe As Boolean
    Public Property TaraeinrichtungSelbsttaetig As Boolean
    Public Property TaraeinrichtungHalbSelbsttaetig As Boolean
    Public Property NullstellungNullnachfuehrung As Boolean
    Public Property NullstellungSelbsttaetig As Boolean
    Public Property NullstellungHalbSelbsttaetig As Boolean

    Public Overridable Property ServerMogelstatistik As ICollection(Of ServerMogelstatistik) = New HashSet(Of ServerMogelstatistik)
    Public Overridable Property ServerEichprozess As ICollection(Of ServerEichprozess) = New HashSet(Of ServerEichprozess)

End Class
