'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerVerbindungsprotokoll
    Public Property ID As Integer
    Public Property Domain As string
    Public Property Computername As string
    Public Property Windowsbenutzer As string
    Public Property Aktion As string
    Public Property Zeitstempel As Nullable(Of Date)
    Public Property Lizenzschluessel_FK As string

End Class
