'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerMogelstatistik
    Public Property ID As Integer
    Public Property FK_Eichprozess As Nullable(Of Integer)
    Public Property FK_Auswertegeraet As string
    Public Property FK_Waegezelle As string
    Public Property Kompatiblitaet_Waage_FabrikNummer As string
    Public Property Kompatiblitaet_Waage_Bauartzulassung As string
    Public Property Kompatiblitaet_Waage_Revisionsnummer As string
    Public Property Kompatiblitaet_Waage_Zulassungsinhaber As string
    Public Property Kompatiblitaet_Waage_Genauigkeitsklasse As string
    Public Property Kompatiblitaet_Waage_AdditiveTarahoechstlast As string
    Public Property Kompatiblitaet_Waage_GrenzenTemperaturbereichMIN As string
    Public Property Kompatiblitaet_Waage_GrenzenTemperaturbereichMAX As string
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertMax_Bereich1 As string
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertE_Bereich1 As string
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertMax_Bereich2 As string
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertE_Bereich2 As string
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertMax_Bereich3 As string
    Public Property Kompatiblitaet_Waage_HoechstlastEichwertE_Bereich3 As string
    Public Property Kompatiblitaet_Waage_Uebersetzungsverhaeltnis As string
    Public Property Kompatiblitaet_Waage_AnzahlWaegezellen As string
    Public Property Kompatiblitaet_Waage_Einschaltnullstellbereich As string
    Public Property Kompatiblitaet_Waage_Ecklastzuschlag As string
    Public Property Kompatiblitaet_Waage_Totlast As string
    Public Property Kompatiblitaet_Waage_Kabellaenge As string
    Public Property Kompatiblitaet_Waage_Kabelquerschnitt As string
    Public Property Kompatiblitaet_AnschriftWaagenbaufirma As string
    Public Property Kompatiblitaet_Verbindungselemente_BruchteilEichfehlergrenze As string
    Public Property Kompatiblitaet_AWG_Anschlussart As string
    Public Property Kompatiblitaet_WZ_Hoechstlast As string

    Public Overridable Property ServerLookup_Auswertegeraet As ServerLookup_Auswertegeraet
    Public Overridable Property ServerLookup_Waegezelle As ServerLookup_Waegezelle
    Public Overridable Property ServerEichprozess As ServerEichprozess

End Class
