'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class View_Eichmarkenverwaltung
    Public Property HE_Kennung As String
    Public Property ID As Integer
    Public Property Benannte_Stelle_Anzahl As Nullable(Of Integer)
    Public Property Eichsiegel_13x13_Anzahl As Nullable(Of Integer)
    Public Property Eichsiegel_Rund_Anzahl As Nullable(Of Integer)
    Public Property Hinweismarke_Gelocht_Anzahl As Nullable(Of Integer)
    Public Property Grünes_M_Anzahl As Nullable(Of Integer)
    Public Property CE_Anzahl As Nullable(Of Integer)
    Public Property Eichsiegel_13x13_Anzahl_Meldestand As Nullable(Of Integer)
    Public Property Eichsiegel_Rund_Anzahl_Meldestand As Nullable(Of Integer)
    Public Property Hinweismarke_Gelocht_Anzahl_Meldestand As Nullable(Of Integer)
    Public Property CE_Anzahl_Meldestand As Nullable(Of Integer)
    Public Property zerstoerte_Marke_0103 As Nullable(Of Integer)
    Public Property Grünes_M_Anzahl_Meldestand As Nullable(Of Integer)
    Public Property Fehlmenge_Benannte_Stelle_0103 As Nullable(Of Integer)
    Public Property Fehlmenge_Benannte_Stelle_0111 As Nullable(Of Integer)
    Public Property Fehlmenge_Sicherungsmarke_Klein As Nullable(Of Integer)
    Public Property Fehlmenge_Sicherungsmarke_Groß As Nullable(Of Integer)
    Public Property Fehlmenge_Hinweismarken As Nullable(Of Integer)
    Public Property Archiv2007_Benannte_Stelle_0298 As String
    Public Property Archiv2007_Hinweismarke As String
    Public Property Archiv2007_Eichungen As String
    Public Property Archiv2007_Sicherungsmarke_Groß As String
    Public Property Archiv2007_Sicherungsmarke_klein As String
    Public Property Archiv2008_Benannte_Stelle_0298 As String
    Public Property Archiv2008_Hinweismarke As String
    Public Property Archiv2008_Eichungen As String
    Public Property Archiv2008_Sicherungsmarke_Groß As String
    Public Property Archiv2008_Sicherungsmarke_klein As String
    Public Property Archiv2009_Eichungen As String
    Public Property Archiv2009_Benannte_Stelle_0298 As String
    Public Property Archiv2009_Hinweismarke As String
    Public Property Archiv2009_Sicherungsmarke_Groß As String
    Public Property Archiv2009_Sicherungsmarke_klein As String
    Public Property Archiv2010_Eichungen As String
    Public Property Archiv2010_Benannte_Stelle_0298 As String
    Public Property Archiv2010_Hinweismarke As String
    Public Property Archiv2010_Sicherungsmarke_Groß As String
    Public Property Archiv2010_Sicherungsmarke_klein As String
    Public Property Archiv2011_Eichungen As String
    Public Property Archiv2011_Benannte_Stelle_0298 As String
    Public Property Archiv2011_Benannte_Stelle_0103 As String
    Public Property Archiv2011_Hinweismarke As String
    Public Property Archiv2011_Sicherungsmarke_Groß As String
    Public Property Archiv2011_Sicherungsmarke_klein As String
    Public Property Archiv2012_Eichungen As String
    Public Property Archiv2012_Benannte_Stelle_0103 As String
    Public Property Archiv2012_Hinweismarke As String
    Public Property Archiv2012_Sicherungsmarke_Groß As String
    Public Property Archiv2013_Eichungen As String
    Public Property Archiv2012_Sicherungsmarke_klein As String
    Public Property Archiv2013_Benannte_Stelle_0103 As String
    Public Property Archiv2013_Hinweismarke As String
    Public Property Archiv2013_Sicherungsmarke_Groß As String
    Public Property Archiv2013_Sicherungsmarke_klein As String
    Public Property Archiv2014_Eichungen As String
    Public Property Archiv2014_Benannte_Stelle_0103 As String
    Public Property Archiv2014_Hinweismarke As String
    Public Property Archiv2014_Benannte_Stelle_0111 As String
    Public Property Archiv2014_Sicherungsmarke_Groß As String
    Public Property Archiv2014_Sicherungsmarke_Klein As String
    Public Property Bemerkung As String
    Public Property Benannte_Stelle_Anzahl_Meldestand As Nullable(Of Integer)

End Class
