'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Eichprozess
    Public Property ID As Integer
    Public Property Vorgangsnummer As String
    Public Property FK_Vorgangsstatus As Byte
    Public Property FK_Auswertegeraet As String
    Public Property FK_Waegezelle As String
    Public Property FK_Beschaffenheitspruefung As Nullable(Of Integer)
    Public Property FK_Eichprotokoll As Nullable(Of Integer)
    Public Property FK_WaagenTyp As Nullable(Of Byte)
    Public Property FK_WaagenArt As Nullable(Of Byte)
    Public Property FK_Kompatibilitaetsnachweis As Nullable(Of Integer)
    Public Property Ausgeblendet As Boolean
    Public Property UploadFilePath As String
    Public Property FK_Bearbeitungsstatus As Nullable(Of Integer)

    Public Overridable Property Beschaffenheitspruefung As Beschaffenheitspruefung
    Public Overridable Property Eichprotokoll As Eichprotokoll
    Public Overridable Property Kompatiblitaetsnachweis As Kompatiblitaetsnachweis
    Public Overridable Property Lookup_Auswertegeraet As Lookup_Auswertegeraet
    Public Overridable Property Lookup_Bearbeitungsstatus As Lookup_Bearbeitungsstatus
    Public Overridable Property Lookup_Vorgangsstatus As Lookup_Vorgangsstatus
    Public Overridable Property Lookup_Waagenart As Lookup_Waagenart
    Public Overridable Property Lookup_Waagentyp As Lookup_Waagentyp
    Public Overridable Property Lookup_Waegezelle As Lookup_Waegezelle
    Public Overridable Property Mogelstatistik As ICollection(Of Mogelstatistik) = New HashSet(Of Mogelstatistik)


    ''' <summary>
    ''' Erzeugt eine Liste von Stati die für den aktuellen Eichrpozess ungültig sind. Z.B. Staffelverfahren bei einbereichwaagen
    ''' </summary>
    ''' <returns></returns>
    ''' <remarks>Wird z.b. für UCOAmpel genutzt umbenötigte Felder auszublenden</remarks>
    Public Function GetListeUngueltigeStati(objEichprozess As Eichprozess) As List(Of GlobaleEnumeratoren.enuEichprozessStatus)
        Try
            Dim returnlist As New List(Of GlobaleEnumeratoren.enuEichprozessStatus)

                'wenn es sich nicht um ein flüchtiges Object handelt (server seitiges objekt (kopie von Server objekt)
                'versuche aufruf,
            Try
                Dim obj = objEichprozess.Eichprotokoll.Lookup_Konformitaetsbewertungsverfahren.Verfahren
                'ansonsten reinitialsiere Objekt aus lokaler DB
                LadeVonServerObjekt(objEichprozess, returnlist)
            Catch ex As Exception
                'neu laden des Objekts, diesmal mit den lookup Objekten
                LadeVonLokalerDB(objEichprozess, returnlist)
            End Try
         






            Return returnlist
        Catch ex As Exception
            Return Nothing
        End Try
    End Function

    Private Sub LadeVonLokalerDB(ByRef objEichprozess As Eichprozess, ByRef returnlist As List(Of GlobaleEnumeratoren.enuEichprozessStatus))
        Using context As New EichsoftwareClientdatabaseEntities1

            objEichprozess = (From a In context.Eichprozess.Include("Lookup_Auswertegeraet").Include("Kompatiblitaetsnachweis").Include("Lookup_Waegezelle").Include("Lookup_Waagenart").Include("Lookup_Waagentyp") Select a Where a.Vorgangsnummer = Me.Vorgangsnummer).FirstOrDefault
            If Not objEichprozess Is Nothing Then
                'Achslastwägungen
                If Not objEichprozess.Eichprotokoll Is Nothing Then
                    Select Case objEichprozess.Eichprotokoll.Lookup_Konformitaetsbewertungsverfahren.Verfahren
                        Case Is = "über 60kg mit Normalien", "über 60kg im Staffelverfahren"
                            ' Wenn der aktuelle Status kleiner ist als der für die Beschaffenheitspruefung, wird dieser überschrieben. Sonst würde ein aktuellere Status mit dem vorherigen überschrieben
                            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.EignungfürAchslastwägungen)
                            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.WaagenFuerRollendeLasten)
                        Case Is = "Fahrzeugwaagen"
                    End Select

                    Select Case objEichprozess.Eichprotokoll.Lookup_Konformitaetsbewertungsverfahren.Verfahren
                        Case Is = "über 60kg mit Normalien"
                            ' Wenn der aktuelle Status kleiner ist als der für die Beschaffenheitspruefung, wird dieser überschrieben. Sonst würde ein aktuellere Status mit dem vorherigen überschrieben
                            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitErsatzlast)
                        Case Is = "Fahrzeugwaagen", "über 60kg im Staffelverfahren"
                            ' Wenn der aktuelle Status kleiner ist als der für die Beschaffenheitspruefung, wird dieser überschrieben. Sonst würde ein aktuellere Status mit dem vorherigen überschrieben
                            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitNormallastLinearitaet)
                    End Select


                    If objEichprozess.Eichprotokoll.Verwendungszweck_Drucker = False Then
                        returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderStabilitätderGleichgewichtslage)
                    End If
                Else
                    returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitNormallastLinearitaet)
                    returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.EignungfürAchslastwägungen)
                    returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.WaagenFuerRollendeLasten)
                    returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitErsatzlast)
                    returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderStabilitätderGleichgewichtslage)
                End If
            Else
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitNormallastLinearitaet)
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.EignungfürAchslastwägungen)
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.WaagenFuerRollendeLasten)
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitErsatzlast)
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderStabilitätderGleichgewichtslage)
            End If
        End Using

    End Sub

    Private Sub LadeVonServerObjekt(ByRef objEichprozess As Eichprozess, ByRef returnlist As List(Of GlobaleEnumeratoren.enuEichprozessStatus))
        If Not objEichprozess Is Nothing Then
            'Achslastwägungen
            If Not objEichprozess.Eichprotokoll Is Nothing Then
                Select Case objEichprozess.Eichprotokoll.Lookup_Konformitaetsbewertungsverfahren.Verfahren
                    Case Is = "über 60kg mit Normalien", "über 60kg im Staffelverfahren"
                        ' Wenn der aktuelle Status kleiner ist als der für die Beschaffenheitspruefung, wird dieser überschrieben. Sonst würde ein aktuellere Status mit dem vorherigen überschrieben
                        returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.EignungfürAchslastwägungen)
                        returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.WaagenFuerRollendeLasten)
                    Case Is = "Fahrzeugwaagen"
                End Select

                Select Case objEichprozess.Eichprotokoll.Lookup_Konformitaetsbewertungsverfahren.Verfahren
                    Case Is = "über 60kg mit Normalien"
                        ' Wenn der aktuelle Status kleiner ist als der für die Beschaffenheitspruefung, wird dieser überschrieben. Sonst würde ein aktuellere Status mit dem vorherigen überschrieben
                        returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitErsatzlast)
                    Case Is = "Fahrzeugwaagen", "über 60kg im Staffelverfahren"
                        ' Wenn der aktuelle Status kleiner ist als der für die Beschaffenheitspruefung, wird dieser überschrieben. Sonst würde ein aktuellere Status mit dem vorherigen überschrieben
                        returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitNormallastLinearitaet)
                End Select


                If objEichprozess.Eichprotokoll.Verwendungszweck_Drucker = False Then
                    returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderStabilitätderGleichgewichtslage)
                End If
            Else
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitNormallastLinearitaet)
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.EignungfürAchslastwägungen)
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.WaagenFuerRollendeLasten)
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitErsatzlast)
                returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderStabilitätderGleichgewichtslage)
            End If
        Else
            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitNormallastLinearitaet)
            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.EignungfürAchslastwägungen)
            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.WaagenFuerRollendeLasten)
            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderRichtigkeitmitErsatzlast)
            returnlist.Add(GlobaleEnumeratoren.enuEichprozessStatus.PrüfungderStabilitätderGleichgewichtslage)
        End If
    End Sub


End Class
