'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class EichsoftwareClientdatabaseEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=EichsoftwareClientdatabaseEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Eichprotokoll() As DbSet(Of Eichprotokoll)
    Public Property Eichprozess() As DbSet(Of Eichprozess)
    Public Property Kompatiblitaetsnachweis() As DbSet(Of Kompatiblitaetsnachweis)
    Public Property Lizensierung() As DbSet(Of Lizensierung)
    Public Property Lookup_Auswertegeraet() As DbSet(Of Lookup_Auswertegeraet)
    Public Property Lookup_Bearbeitungsstatus() As DbSet(Of Lookup_Bearbeitungsstatus)
    Public Property Lookup_Konformitaetsbewertungsverfahren() As DbSet(Of Lookup_Konformitaetsbewertungsverfahren)
    Public Property Lookup_Vorgangsstatus() As DbSet(Of Lookup_Vorgangsstatus)
    Public Property Lookup_Waagenart() As DbSet(Of Lookup_Waagenart)
    Public Property Lookup_Waagentyp() As DbSet(Of Lookup_Waagentyp)
    Public Property Lookup_Waegezelle() As DbSet(Of Lookup_Waegezelle)
    Public Property Mogelstatistik() As DbSet(Of Mogelstatistik)
    Public Property PruefungAnsprechvermoegen() As DbSet(Of PruefungAnsprechvermoegen)
    Public Property PruefungAussermittigeBelastung() As DbSet(Of PruefungAussermittigeBelastung)
    Public Property PruefungLinearitaetFallend() As DbSet(Of PruefungLinearitaetFallend)
    Public Property PruefungLinearitaetSteigend() As DbSet(Of PruefungLinearitaetSteigend)
    Public Property PruefungRollendeLasten() As DbSet(Of PruefungRollendeLasten)
    Public Property PruefungStabilitaetGleichgewichtslage() As DbSet(Of PruefungStabilitaetGleichgewichtslage)
    Public Property PruefungStaffelverfahrenErsatzlast() As DbSet(Of PruefungStaffelverfahrenErsatzlast)
    Public Property PruefungStaffelverfahrenNormallast() As DbSet(Of PruefungStaffelverfahrenNormallast)
    Public Property PruefungWiederholbarkeit() As DbSet(Of PruefungWiederholbarkeit)

End Class
