'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Konfiguration
    Public Property BenutzerLizenz As String
    Public Property LetztesUpdate As Date
    Public Property AktuelleSprache As String
    Public Property Synchronisierungsmodus As String
    Public Property SyncAb As Date
    Public Property SyncBis As Date
    Public Property HoleAlleeigenenEichungenVomServer As Boolean
    Public Property GridSettings As String
    Public Property GridSettingsRHEWA As String
    Public Property DBVersion As String

End Class
