'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Konfiguration
    Public Property BenutzerLizenz As String
    Public Property LetztesUpdate As Date
    Public Property AktuelleSprache As String
    Public Property Synchronisierungsmodus As String
    Public Property SyncAb As Date
    Public Property SyncBis As Date
    Public Property HoleAlleeigenenEichungenVomServer As Boolean
    Public Property GridSettings As String
    Public Property GridSettingsRHEWA As String

End Class
