'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Lizensierung
    Public Property ID As Integer
    Public Property Lizenzschluessel As String
    Public Property LetzteAktivierung As Nullable(Of Date)
    Public Property RHEWALizenz As Boolean
    Public Property Aktiv As Boolean
    Public Property FK_Benutzer As String
    Public Property FirmaOrt As String
    Public Property Firma As String
    Public Property Vorname As String
    Public Property Name As String
    Public Property FirmaPLZ As String
    Public Property FirmaStrasse As String

End Class
