'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Lookup_Konformitaetsbewertungsverfahren
    Public Property ID As Byte
    Public Property Verfahren As string
    Public Property Verfahren_EN As string
    Public Property Verfahren_PL As string

    Public Overridable Property Eichprotokoll As ICollection(Of Eichprotokoll) = New HashSet(Of Eichprotokoll)

End Class
