'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PruefungAnsprechvermoegen
    Public Property ID As Integer
    Public Property FK_Eichprotokoll As Integer
    Public Property LastL As String
    Public Property Last As String
    Public Property Anzeige As String
    Public Property Last1d As String
    Public Property Ziffernsprung As Boolean

    Public Overridable Property Eichprotokoll As Eichprotokoll

End Class
