'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PruefungStabilitaetGleichgewichtslage
    Public Property ID As Integer
    Public Property FK_Eichprotokoll As Integer
    Public Property Durchlauf As Byte
    Public Property Last As String
    Public Property Anzeige As String
    Public Property MIN As String
    Public Property MAX As String
    Public Property AbdruckOK As Boolean

    Public Overridable Property Eichprotokoll As Eichprotokoll

End Class
