'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PruefungRollendeLasten
    Public Property ID As Integer
    Public Property FK_Eichprotokoll As Integer
    Public Property Belastungsstelle As Byte
    Public Property AuffahrtSeite As String
    Public Property Last As String
    Public Property Anzeige As String
    Public Property Fehler As String
    Public Property EFG As String
    Public Property EFGExtra As String

    Public Overridable Property Eichprotokoll As Eichprotokoll

End Class
