'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Benutzer
    Public Property ID As String
    Public Property Vorname As String
    Public Property Nachname As String
    Public Property Telefon As String
    Public Property HEKennung As String
    Public Property Firma_FK As String

    Public Overridable Property Firmen As Firmen
    Public Overridable Property ServerLizensierung As ICollection(Of ServerLizensierung) = New HashSet(Of ServerLizensierung)

End Class
