'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Firmen
    Public Property ID As string
    Public Property KundenNr As string
    Public Property Name As string
    Public Property Strasse As string
    Public Property PLZ As string
    Public Property Telefon As string
    Public Property Ort As string
    Public Property Land As string

    Public Overridable Property Benutzer As ICollection(Of Benutzer) = New HashSet(Of Benutzer)
    Public Overridable Property ServerFirmenZusatzdaten As ICollection(Of ServerFirmenZusatzdaten) = New HashSet(Of ServerFirmenZusatzdaten)

End Class
