'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerKonfiguration
    Public Property ID As Integer
    Public Property LetzteSynchronisierungMitRHEWA As Nullable(Of Date)
    Public Property NetzwerkpfadFuerDateianhaenge As String
    Public Property FTPServerAdresse As String
    Public Property FTPServerBenutzername As String
    Public Property FTPServerEnkodiertesPasswort As String
    Public Property FTPServerCryptoSaltKey As String

End Class
