'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerBeschaffenheitspruefung
    Public Property ID As Integer
    Public Property AWG_Auslieferungszustand As Boolean
    Public Property AWG_MetrologischeAngabenVorhanden As Boolean
    Public Property AWG_KabelUnbeschaedigt As Boolean
    Public Property WZ_ZulassungOIMLR60 As Boolean
    Public Property WZ_KrafteinteilungKonformWELMEC As Boolean
    Public Property WZ_KabelUnbeschaedigt As Boolean
    Public Property WZ_AnschraubplattenEben As Boolean
    Public Property WZ_VergussUnbeschaedigt As Boolean
    Public Property Verbindungselemente_DichtigkeitGegeben As Boolean
    Public Property Verbindungselemente_KabelUnbeschaedigt As Boolean
    Public Property Verbindungselemente_KabelNichtSproede As Boolean
    Public Property Verbindungselemente_KabelTemperaturGeschuetzt As Boolean
    Public Property Waegebruecke_WiegeaufgabeAusgelegt As Boolean
    Public Property Waegebruecke_Korrosionsfrei As Boolean
    Public Property Waegebruecke_WZAufnahmenInEbene As Boolean

    Public Overridable Property ServerEichprozess As ICollection(Of ServerEichprozess) = New HashSet(Of ServerEichprozess)

End Class
