'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerEichmarkenverwaltung
    Public Property ID As Integer
    Public Property FK_BenutzerID As String
    Public Property HEKennung As String
    Public Property BenannteStelleAnzahl As Nullable(Of Integer)
    Public Property BenannteStelleAnzahlMeldestand As Nullable(Of Integer)
    Public Property BenannteStelleFehlmenge As Nullable(Of Integer)
    Public Property BenannteStelleAnzahlAusgeteilt As Nullable(Of Integer)
    Public Property SicherungsmarkeKleinAnzahl As Nullable(Of Integer)
    Public Property SicherungsmarkeKleinAnzahlMeldestand As Nullable(Of Integer)
    Public Property SicherungsmarkeKleinFehlmenge As Nullable(Of Integer)
    Public Property SicherungsmarkeKleinAnzahlAusgeteilt As Nullable(Of Integer)
    Public Property SicherungsmarkeGrossAnzahl As Nullable(Of Integer)
    Public Property SicherungsmarkeGrossAnzahlMeldestand As Nullable(Of Integer)
    Public Property SicherungsmarkeGrossFehlmenge As Nullable(Of Integer)
    Public Property SicherungsmarkeGrossAnzahlAusgeteilt As Nullable(Of Integer)
    Public Property HinweismarkeAnzahl As Nullable(Of Integer)
    Public Property HinweismarkeAnzahlMeldestand As Nullable(Of Integer)
    Public Property HinweismarkeFehlmenge As Nullable(Of Integer)
    Public Property HinweismarkeAnzahlAusgeteilt As Nullable(Of Integer)
    Public Property Bemerkung As String
    Public Property ZurBearbeitungGesperrtDurch As String

End Class
