'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerKonfiguration
    Public Property ID As Integer
    Public Property LetzteSynchronisierungMitRHEWA As Nullable(Of Date)
    Public Property NetzwerkpfadFuerDateianhaenge As String
    Public Property FTPServerAdresse As String
    Public Property FTPServerBenutzername As String
    Public Property FTPServerEnkodiertesPasswort As String
    Public Property FTPServerCryptoSaltKey As String

End Class
