'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerKompatiblitaetsnachweis
    Public Property ID As Integer
    Public Property Kompatiblitaet_Waage_Hoechstlast1 As String
    Public Property Kompatiblitaet_Waage_Hoechstlast2 As String
    Public Property Kompatiblitaet_Waage_Hoechstlast3 As String
    Public Property Kompatiblitaet_Waage_Eichwert1 As String
    Public Property Kompatiblitaet_Waage_Eichwert2 As String
    Public Property Kompatiblitaet_Waage_Eichwert3 As String
    Public Property Kompatiblitaet_Waage_FabrikNummer As String
    Public Property Kompatiblitaet_Waage_Bauartzulassung As String
    Public Property Kompatiblitaet_Waage_Revisionsnummer As String
    Public Property Kompatiblitaet_Waage_Zulassungsinhaber As String
    Public Property Kompatiblitaet_Waage_Genauigkeitsklasse As String
    Public Property Kompatiblitaet_Waage_AdditiveTarahoechstlast As String
    Public Property Kompatiblitaet_Waage_GrenzenTemperaturbereichMIN As String
    Public Property Kompatiblitaet_Waage_GrenzenTemperaturbereichMAX As String
    Public Property Kompatiblitaet_Waage_Uebersetzungsverhaeltnis As String
    Public Property Kompatiblitaet_Waage_AnzahlWaegezellen As String
    Public Property Kompatiblitaet_Waage_Einschaltnullstellbereich As String
    Public Property Kompatiblitaet_Waage_Ecklastzuschlag As String
    Public Property Kompatiblitaet_Waage_Totlast As String
    Public Property Kompatiblitaet_Waage_Kabellaenge As String
    Public Property Kompatiblitaet_Waage_Kabelquerschnitt As String
    Public Property Kompatiblitaet_Verbindungselemente_BruchteilEichfehlergrenze As String
    Public Property Kompatiblitaet_Hersteller As String
    Public Property Kompatiblitaet_Strasse As String
    Public Property Kompatiblitaet_Ort As String
    Public Property Kompatiblitaet_Postleitzahl As String
    Public Property Kompatiblitaet_AWG_Anschlussart As String
    Public Property Kompatiblitaet_WZ_Hoechstlast As String

End Class
