'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerPruefungLinearitaetFallend
    Public Property ID As Integer
    Public Property FK_Eichprotokoll As Integer
    Public Property Bereich As Byte
    Public Property Messpunkt As String
    Public Property Last As String
    Public Property Anzeige As String
    Public Property Fehler As String
    Public Property EFG As String

    Public Overridable Property ServerEichprotokoll As ServerEichprotokoll

End Class
