'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerFirmenZusatzdaten
    Public Property ID As String
    Public Property Firmen_FK As String
    Public Property Umsatz As String
    Public Property Abrechnungsmodell As String
    Public Property Qualifizierungspauschale As String
    Public Property BeginnVertrag As Nullable(Of Date)
    Public Property EndeVertrag As Nullable(Of Date)
    Public Property Erstschulung As Nullable(Of Date)
    Public Property MonatJahrZertifikat As String
    Public Property Nachschulung As Nullable(Of Date)
    Public Property LetztesAudit As Nullable(Of Date)

End Class
