'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerLookup_Konformitaetsbewertungsverfahren
    Public Property ID As Byte
    Public Property Verfahren As String
    Public Property Verfahren_EN As String
    Public Property Verfahren_PL As String

    Public Overridable Property ServerEichprotokoll As ICollection(Of ServerEichprotokoll) = New HashSet(Of ServerEichprotokoll)

End Class
