'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerPruefungStaffelverfahrenErsatzlast
    Public Property ID As Integer
    Public Property FK_Eichprotokoll As Integer
    Public Property Staffel As Byte
    Public Property Bereich As Byte
    Public Property Ersatzlast_Soll As string
    Public Property Ersatzlast_Ist As string
    Public Property ZusaetzlicheErsatzlast_Soll As string
    Public Property ErsatzUndNormallast_Soll As string
    Public Property ErsatzUndNormallast_Ist As string
    Public Property Ersatzlast2_Soll As string
    Public Property Ersatzlast2_Ist As string
    Public Property DifferenzAnzeigewerte_Fehler As string
    Public Property DifferenzAnzeigewerte_EFG As string
    Public Property MessabweichungStaffel_Fehler As string
    Public Property MessabweichungStaffel_EFG As string
    Public Property MessabweichungWaage_Fehler As string
    Public Property MessabweichungWaage_EFG As string

    Public Overridable Property ServerEichprotokoll As ServerEichprotokoll

End Class
