'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerPruefungEichfehlergrenzen
    Public Property ID As Integer
    Public Property FK_Eichprotokoll As Integer
    Public Property Messbereich As Byte
    Public Property Elemente As String
    Public Property Von As String
    Public Property Bis As String
    Public Property EFG As String
    Public Property VFG As String

    Public Overridable Property ServerEichprotokoll As ServerEichprotokoll

End Class
