'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerPruefungEichfehlergrenzen
    Public Property ID As Integer
    Public Property FK_Eichprotokoll As Integer
    Public Property Messbereich As Byte
    Public Property Elemente As String
    Public Property Von As String
    Public Property Bis As String
    Public Property EFG As String
    Public Property VFG As String

    Public Overridable Property ServerEichprotokoll As ServerEichprotokoll

End Class
