'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerFirmenZusatzdaten
    Public Property ID As String
    Public Property Firmen_FK As String
    Public Property Abrechnungsmodell As String
    Public Property Qualifizierungspauschale As String
    Public Property BeginnVertrag As Nullable(Of Date)
    Public Property EndeVertrag As Nullable(Of Date)
    Public Property Erstschulung As Nullable(Of Date)
    Public Property MonatJahrZertifikat As String
    Public Property Nachschulung As Nullable(Of Date)
    Public Property LetztesAudit As Nullable(Of Date)

    Public Overridable Property Firmen As Firmen

End Class
