'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ServerPruefungAnsprechvermoegen
    Public Property ID As Integer
    Public Property FK_Eichprotokoll As Integer
    Public Property LastL As String
    Public Property Last As String
    Public Property Anzeige As String
    Public Property Last1d As String
    Public Property Ziffernsprung As Boolean

    Public Overridable Property ServerEichprotokoll As ServerEichprotokoll

End Class
