'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EichsoftwareClient.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _0405_Beschilderung_Auswertegeraet_Frontseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0405_Beschilderung_Auswertegeraet_Frontseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _0405_Beschilderung_Auswertegeraet_Frontseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0405_Beschilderung_Auswertegeraet_Frontseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _0405_Beschilderung_Auswertegeraet_Rueckseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0405_Beschilderung_Auswertegeraet_Rueckseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _0405_Beschilderung_Auswertegeraet_Rueckseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0405_Beschilderung_Auswertegeraet_Rueckseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Alpha_Beschilderung_Auswertegeraet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Alpha_Beschilderung_Auswertegeraet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Alpha_Beschilderung_Auswertegeraet_Frontseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Alpha_Beschilderung_Auswertegeraet_Frontseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Alpha_Beschilderung_Auswertegeraet_Frontseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Alpha_Beschilderung_Auswertegeraet_Frontseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Alpha_Beschilderung_Auswertegeraet_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Alpha_Beschilderung_Auswertegeraet_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Alpha_CEXY_Auswertegeraet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Alpha_CEXY_Auswertegeraet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Alpha_CEXY_Auswertegeraet_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Alpha_CEXY_Auswertegeraet_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Basic_Beschilderung_Auswertegeraet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Basic_Beschilderung_Auswertegeraet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Basic_Beschilderung_Auswertegeraet_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Basic_Beschilderung_Auswertegeraet_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Basic_Beschilderung_Auswertegeraet_Unterseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Basic_Beschilderung_Auswertegeraet_Unterseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Basic_Beschilderung_Auswertegeraet_Unterseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Basic_Beschilderung_Auswertegeraet_Unterseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Basic_CEXY_Auswertegeraet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Basic_CEXY_Auswertegeraet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _82Basic_CEXY_Auswertegeraet_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_82Basic_CEXY_Auswertegeraet_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83N_Beschilderung_Auswertegeraet_Frontseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83N_Beschilderung_Auswertegeraet_Frontseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83N_Beschilderung_Auswertegeraet_Frontseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83N_Beschilderung_Auswertegeraet_Frontseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83N_Beschilderung_Auswertegeraet_Rueckseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83N_Beschilderung_Auswertegeraet_Rueckseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83N_Beschilderung_Auswertegeraet_Rueckseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83N_Beschilderung_Auswertegeraet_Rueckseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83Plus_Beschilderung_Auswertegeraet_Frontseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83Plus_Beschilderung_Auswertegeraet_Frontseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83Plus_Beschilderung_Auswertegeraet_Frontseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83Plus_Beschilderung_Auswertegeraet_Frontseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83Plus_Beschilderung_Auswertegeraet_Rueckseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83Plus_Beschilderung_Auswertegeraet_Rueckseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83Plus_Beschilderung_Auswertegeraet_Rueckseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83Plus_Beschilderung_Auswertegeraet_Rueckseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83Z_Beschilderung_Auswertegeraet_Frontseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83Z_Beschilderung_Auswertegeraet_Frontseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83Z_Beschilderung_Auswertegeraet_Frontseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83Z_Beschilderung_Auswertegeraet_Frontseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83Z_Beschilderung_Auswertegeraet_Rueckseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83Z_Beschilderung_Auswertegeraet_Rueckseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _83Z_Beschilderung_Auswertegeraet_Rueckseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_83Z_Beschilderung_Auswertegeraet_Rueckseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _84_Beschilderung_Auswertegeraet_Frontseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_84_Beschilderung_Auswertegeraet_Frontseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _84_Beschilderung_Auswertegeraet_Frontseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_84_Beschilderung_Auswertegeraet_Frontseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _84_Beschilderung_Auswertegeraet_Rueckseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_84_Beschilderung_Auswertegeraet_Rueckseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _84_Beschilderung_Auswertegeraet_Rueckseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_84_Beschilderung_Auswertegeraet_Rueckseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _92_Beschilderung_Auswertegeraet_Frontseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_92_Beschilderung_Auswertegeraet_Frontseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _92_Beschilderung_Auswertegeraet_Frontseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_92_Beschilderung_Auswertegeraet_Frontseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _92_Beschilderung_Auswertegeraet_Rueckseite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_92_Beschilderung_Auswertegeraet_Rueckseite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _92_Beschilderung_Auswertegeraet_Rueckseite_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_92_Beschilderung_Auswertegeraet_Rueckseite_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bullet_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bullet_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bullet_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EightLCs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EightLCs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Equation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Equation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ersteichung_DE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ersteichung_DE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Ersteichung_EN() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ersteichung_EN", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Ersteichung_PL() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ersteichung_PL", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Fahrzeug_Wenden_DE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fahrzeug_Wenden_DE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fahrzeug_Wenden_GB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fahrzeug_Wenden_GB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fahrzeug_Wenden_PL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fahrzeug_Wenden_PL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag_germany() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_germany", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag_poland() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_poland", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag_usa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_usa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FourLCs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FourLCs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Genauigkeitsklasse1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Genauigkeitsklasse1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Genauigkeitsklasse2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Genauigkeitsklasse2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Genauigkeitsklasse3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Genauigkeitsklasse3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Genauigkeitsklasse4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Genauigkeitsklasse4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kompatibilitätsnachweis_DE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Kompatibilitätsnachweis_DE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Kompatibilitätsnachweis_EN() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Kompatibilitätsnachweis_EN", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Konformitätserklärung_DE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Konformitätserklärung_DE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Konformitätserklärung_PL() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Konformitätserklärung_PL", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Konformitätserklärung_RO() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Konformitätserklärung_RO", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property LKW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LKW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LKW_Gedreht() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LKW_Gedreht", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resultset_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resultset_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resultset_previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resultset_previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RHEWA_Logo_35mm_600dpi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RHEWA_Logo_35mm_600dpi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RHEWAGREEN() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RHEWAGREEN", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SixLCs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SixLCs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TwelveLCs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TwelveLCs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Verschiebeweg_DE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Verschiebeweg_DE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Verschiebeweg_GB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Verschiebeweg_GB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Verschiebeweg_PL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Verschiebeweg_PL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weighing_mashine() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("weighing_mashine", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
